/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agendamedicale;
import agendamedicale.login;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
/**
 *
 * @author kloug
 */
public class AgMed extends javax.swing.JFrame {
    
    private Connection connection;
    private PreparedStatement preparedStatement;
    
    
    // Connection à la base de donnée 
    public  Connection conn(){
    /*
        try{
            
            String url = "jdbc:mysql://localhost:3307/bd_rdv"; //définition de l’URL de connexion a la  base de données  
            Class.forName("com.mysql.cj.jdbc.Driver"); // chargement  dynamique du  driver JDBC de MySQL
            Connection conn  = DriverManager.getConnection(url);
            return conn;
        //Verification  si le driver JDBC a été trouver
        }catch(SQLException  | ClassNotFoundException e)    {
        
                JOptionPane.showMessageDialog(null, e);
        
        }*/
        
            String url = "jdbc:mysql://localhost:3307/bd_rdv"; //définition de l’URL de connexion a la  base de données  
            String user = "samson"; // Remplacez par votre nom d'utilisateur MySQL XAMPP
            String password = ""; // Remplacez par votre mot de passe MySQL XAMPP

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(url, user, password);
                // ...
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erreur de connexion à la base de données : " + e.getMessage());
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Pilote JDBC MySQL non trouvé.");
                e.printStackTrace();
            }
        
            return connection;
            
        
        
        
        
        
        
        
        
        
        
      //  return null;
    
    } 

    /**
     * Creates new form AgMed
     */
    public AgMed() {
        initComponents();
        connection  = conn();
        chargerSpecialites();
        chargerMedecin("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        motif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        specialite = new javax.swing.JComboBox<>();
        AjouterRdv = new javax.swing.JButton();
        AnnulerRdv = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        date_rdv = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        ModifierRdv = new javax.swing.JButton();
        VoirListRdv = new javax.swing.JButton();
        ActualiserRdv = new javax.swing.JButton();
        medecin = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        heure_rdv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VOIR LA LISTE DES RDV");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });

        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });

        motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("PRISE DE RENDEZ VOUS MEDICALE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Prenom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Telephone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Adresse");

        adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Motif");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("Specialite");

        specialite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        specialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialiteActionPerformed(evt);
            }
        });

        AjouterRdv.setBackground(new java.awt.Color(51, 0, 51));
        AjouterRdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AjouterRdv.setForeground(new java.awt.Color(255, 255, 255));
        AjouterRdv.setText("AJOUTER UN RDV");
        AjouterRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterRdvActionPerformed(evt);
            }
        });

        AnnulerRdv.setBackground(new java.awt.Color(255, 0, 51));
        AnnulerRdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AnnulerRdv.setForeground(new java.awt.Color(255, 255, 255));
        AnnulerRdv.setText("ANNULER RDV");
        AnnulerRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerRdvActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("Age");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("Medecin");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Date ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("Heure");

        ModifierRdv.setBackground(new java.awt.Color(51, 255, 51));
        ModifierRdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ModifierRdv.setForeground(new java.awt.Color(255, 255, 255));
        ModifierRdv.setText("MODIFIER RDV");
        ModifierRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierRdvActionPerformed(evt);
            }
        });

        VoirListRdv.setBackground(new java.awt.Color(102, 102, 255));
        VoirListRdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VoirListRdv.setForeground(new java.awt.Color(255, 255, 255));
        VoirListRdv.setText("VOIR LISTE RDV");
        VoirListRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoirListRdvActionPerformed(evt);
            }
        });

        ActualiserRdv.setBackground(new java.awt.Color(255, 102, 0));
        ActualiserRdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ActualiserRdv.setForeground(new java.awt.Color(255, 255, 255));
        ActualiserRdv.setText("ACTUALISER");
        ActualiserRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualiserRdvActionPerformed(evt);
            }
        });

        medecin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("LISTES DES RENDEZ VOUS ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom du patient", "Prenom ", "Telephone", "Motif", "Adresse", "Medecin", "Date", "Heure"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(358, 358, 358)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(heure_rdv, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(AjouterRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(AnnulerRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(ModifierRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(VoirListRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ActualiserRdv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(adresse, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addComponent(nom))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(medecin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(motif)
                                            .addComponent(date_rdv, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(telephone))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(234, 234, 234))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(age))))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel12)))
                .addGap(463, 463, 463))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(motif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(medecin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_rdv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(heure_rdv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnnulerRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoirListRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualiserRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton2)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1089, 893));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motifActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnnulerRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerRdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnnulerRdvActionPerformed

    private void VoirListRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoirListRdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoirListRdvActionPerformed

    private void ModifierRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierRdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierRdvActionPerformed

    private void ActualiserRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualiserRdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualiserRdvActionPerformed

    private void adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseActionPerformed

    private void AjouterRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterRdvActionPerformed
        // TODO add your handling code here:
            String Nom = nom.getText();
            String Prenom = prenom.getText();
            String Telephone = telephone.getText();
            String Age = age.getText();
            String Adresse = adresse.getText();
            String Motif = motif.getText();
            String Specialite = (String) specialite.getSelectedItem();
            String Medecin = (String) medecin.getSelectedItem();
            //Récupérer la date et afficher une erreur si une date n'est pas selectionné
            java.util.Date selectedUtilDate = date_rdv.getDate();
            String dateRdvString = null;
            if(selectedUtilDate != null){
                SimpleDateFormat  sdf  = new SimpleDateFormat("yyyy-MM-dd");
                dateRdvString = sdf.format(selectedUtilDate);
            }else{
                
                    JOptionPane.showMessageDialog(this,"Veuillez choisir une date ","Erreur",JOptionPane.WARNING_MESSAGE);
                    return;
            
            }
            String Heure = heure_rdv.getText();
            if(Heure.isEmpty()){
                
                JOptionPane.showMessageDialog(this,"Veuillez choisir une heure ","erreur",JOptionPane.WARNING_MESSAGE);
            }
            // si les champ ne sont pas saisis
            if(Nom.isEmpty()|| Prenom.isEmpty()||Specialite==null||Medecin==null||selectedUtilDate==null||Motif.isEmpty()||Telephone.isEmpty()||Adresse.isEmpty()||Age.isEmpty()||Heure.isEmpty()){
                
                JOptionPane.showMessageDialog(this,"Veuillez remplir tous les champs obligatoire","Erreur",JOptionPane.WARNING_MESSAGE);
                return;
            
            }
            int id_patient =-1;
                try{
                                 String insertPatientQuery = "INSERT INTO patient (nom, prenom, telephone, adresse, age,motif) VALUES (?, ?, ?, ?, ?,?)";
                                preparedStatement = connection.prepareStatement(insertPatientQuery, java.sql.Statement.RETURN_GENERATED_KEYS);
                                // ... définir les paramètres pour le patient ...
                                
                                preparedStatement.setString(1,Nom);
                                preparedStatement.setString(2, Prenom);
                                preparedStatement.setString(3,Telephone);
                                preparedStatement.setString(4,Adresse);
                                preparedStatement.setString(5,Age);
                                preparedStatement.setString(6, Motif);
                                preparedStatement.executeUpdate();
                                ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
                                if (generatedKeys.next()) {
                                    id_patient = generatedKeys.getInt(1); // Récupérer l'ID généré
                                } 
                                generatedKeys.close();

                }catch (SQLException ex){
                
                          JOptionPane.showMessageDialog(this,"Erreur lors de l'enregistrement"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                          return;
                
                
                }finally { //nouvelle ligne 
                    
                    if(preparedStatement !=null){
                        try{
                                preparedStatement.close();
                        }catch (SQLException ex){
                            ex.printStackTrace();
                        }
                    }
                }
                
              
                /*
                try{
                                 String selectPatientQuery = "SELECT id_patient FROM patient WHERE nom = ? AND prenom = ?"; // Assurez-vous du nom de la colonne ID
                                preparedStatement = connection.prepareStatement(selectPatientQuery);
                                // ... définir les paramètres pour la recherche du patient ...
                                ResultSet patientResult = preparedStatement.executeQuery();
                                if (patientResult.next()) {
                                    id_patient = patientResult.getInt("id_patient"); // Récupérer l'ID existant
                                    // ... (éventuellement mettre à jour d'autres infos du patient) ...
                                } 
                                patientResult.close();
                }catch (SQLException ex){
                    
                     JOptionPane.showMessageDialog(this,"Erreur de récupération de l id "+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                      return;
                
                }*/
                
               if(id_patient !=-1){
               
                                  try{
                                  
                                            String insertRendezvousQuery = "INSERT INTO rendezvous (id_patient,id_medecin,date_rdv,heure_rdv) VALUES(?,?,?,?)";
                                            preparedStatement = connection.prepareStatement(insertRendezvousQuery);
                                            preparedStatement.setInt(1,id_patient);
                                            preparedStatement.setInt(2, Integer.parseInt(Medecin.split(" - ")[0]));
                                           // preparedStatement.setString(3, Motif);
                                            preparedStatement.setString(3,dateRdvString);
                                            preparedStatement.setString(4, Heure);
                                            preparedStatement.executeUpdate();
                                            JOptionPane.showMessageDialog(this,"le rendez vous a été enregistré");
                                            nom.setText("");
                                            prenom.setText("");
                                            adresse.setText("");
                                           // motif.setText("");
                                            date_rdv.setDate(null);
                                            heure_rdv.setText("");
                                            specialite.setSelectedIndex(0);
                                            chargerMedecin("");
                                            afficherRendezVousDansTable();
                                            
                                            
                                            
                                  
                                  }catch(SQLException ex ){
                                            JOptionPane.showMessageDialog(this,"Erreur de enregistrement :"+ex.getMessage(),"erreur",JOptionPane.ERROR_MESSAGE);
                                  
                                  }finally{
                                  
                                            if(preparedStatement != null){
                                                        
                                                        try{
                                                                    preparedStatement.close(); 
                                                        
                                                        } catch(SQLException ex) {
                                                            ex.printStackTrace();
                                                        
                                                        }
                                            
                                            
                                            }
                                  
                                  }
               
               }

                                
                                

            
           /* int id_medecin = -1;
            try {
                
                String selectMedecinIdQuery = "SELECT id_medecin FROM medecin WHERE nom = ? AND specialite = ?";
                preparedStatement = connection.prepareStatement(selectMedecinIdQuery);
                preparedStatement.setString(1,Nom);
                preparedStatement.setString(2,Specialite);
                ResultSet medecinResult = preparedStatement.executeQuery();
                if ( medecinResult.next()){
                    
                    id_medecin = medecinResult.getInt("id_medecin");
                    
                
                }
                medecinResult.close();
            
            }catch(SQLException ex){
                
                JOptionPane.showMessageDialog(this,"Erreur de récupération de l id "+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                return;
            
            }*/
            /*if(id_medecin != -1){
            
                        try{
                            
                            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                            dateRdvString = sdf.format(selectedUtilDate);
                            
                                String insertRendezvousQuery = "INSERT INTO rendezvous (id_patient,id_medecin, motif, date_rdv, heure_rdv) VALUES (?, ?, ?, ?, ?)";
                                PreparedStatement insertRdvStmt = connection.prepareStatement(insertRendezvousQuery);
                                insertRdvStmt.setInt(1, id_patient); // Assurez-vous d'avoir récupéré l'ID du patient
                                insertRdvStmt.setInt(2, id_medecin);
                                insertRdvStmt.setString(3, Motif);
                                insertRdvStmt.setString(4, dateRdvString);
                                insertRdvStmt.setString(5, Heure);
                                insertRdvStmt.executeUpdate();
                                insertRdvStmt.close();
                                JOptionPane.showMessageDialog(this,"Le rendez-vous a été enrégistré ");
                            
                        
                        }catch(SQLException ex) 
                                {
                                        JOptionPane.showMessageDialog(this,"Erreur lors de l'enregistrement"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                        
                        }
            
            }*/           
    }//GEN-LAST:event_AjouterRdvActionPerformed

private void chargerSpecialites(){
        
        specialite.removeAllItems();
        try {
        
                String query = "SELECT DISTINCT specialite FROM medecin";
                preparedStatement = connection.prepareStatement(query);
                ResultSet resultSet = preparedStatement.executeQuery();
                
                while(resultSet.next()){
                        
                      specialite.addItem(resultSet.getString("specialite"));
                        
                }
                resultSet.close();
        }catch (SQLException ex){
                
            JOptionPane.showMessageDialog(this,"Erreur chargement"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
            System.err.println("Erreur chargement specialites"+ex.getMessage());
        }    
    }
    
   // chargement des données de l'attribut nom du medecin contenus dans la table medecin
    
    private void chargerMedecin(String specialite){
        
        medecin.removeAllItems();
        if(specialite !=null && !specialite.isEmpty()){
        
            try {
                    String query = "SELECT id_medecin, nom FROM medecin WHERE specialite = ?";
                    preparedStatement = connection.prepareStatement(query);
                    preparedStatement.setString(1,specialite);
                    ResultSet resultSet = preparedStatement.executeQuery();
                    while(resultSet.next()){
                        int idmedecin = resultSet.getInt("id_medecin");
                        String nom = resultSet.getString("nom");
                        medecin.addItem(idmedecin+" - "+nom);
                    
                    }
                    resultSet.close();
            
            
            }catch(SQLException ex) {
            
                JOptionPane.showMessageDialog(this,"Erreur du chargement"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                System.err.println("Erreur chargement medecin"+ex.getMessage());
            }finally {
            
                        try {
                                
                                if (preparedStatement !=null) preparedStatement.close();
                        }catch (SQLException ex){
                                ex.printStackTrace();
                        
                        }
            
            }
        
        }else {
            try{
            
                    String query = "SELECT id_medecin, nom from medecin";
                    preparedStatement = connection.prepareStatement(query);
                    ResultSet resultSet = preparedStatement.executeQuery();
                    while(resultSet.next()){
                            int idmedecin = resultSet.getInt("id_medecin");
                            String nom = resultSet.getString("nom");
                            medecin.addItem(idmedecin+" - "+nom);
                    }
                    resultSet.close();
            }catch (SQLException ex){
            
                        JOptionPane.showMessageDialog(this,"Erreur chargement"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                        System.err.println("Erreur chargement medecins"+ex.getMessage());
            }finally {
                    try {
                    
                      if(preparedStatement != null) preparedStatement.close();
                    }catch(SQLException ex){
                        ex.printStackTrace();      
           }
        
        }
    
    }
    }
        
        
        
    private void specialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialiteActionPerformed
        // TODO add your handling code here:
        
        String Specialite = (String) specialite.getSelectedItem();
        chargerMedecin(Specialite);
    }//GEN-LAST:event_specialiteActionPerformed

    // Charger les specialite contenu dans la table medecin 
    
    private void afficherRendezVousDansTable(){
         //afficher les données dans la table        
        try {
            String query = "SELECT p.nom, p.prenom, p.telephone, p.motif, p.adresse, m.nom, m.prenom, r.date_rdv, r.heure_rdv FROM rendezvous r JOIN patient p ON r.id_patient = p.id_patient JOIN medecin m ON r.id_medecin = m.id_medecin";
            preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement .executeQuery();
            
            //récupération des info de la table 
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                        String nomPatient = rs.getString("p.nom");
                        String prenomPatient = rs.getString("p.prenom");
                        String telephone = rs.getString("p.telephone");
                        String motifRdv = rs.getString("p.motif");
                        String adresse = rs.getString("p.adresse");
                        String nomMedecin = rs.getString("m.nom");
                        String dateRdv = rs.getString("r.date_rdv");
                        String heureRdv = rs.getString("r.heure_rdv");
                        
                        model.addRow(new Object[]{nomPatient,prenomPatient,telephone,motifRdv,adresse,nomMedecin,dateRdv,heureRdv});
                    
            }
            rs.close();
        
        
        }catch (SQLException ex){
                
                JOptionPane.showMessageDialog(this,"Erreur lors de l'affichage des rendez vous"+ex.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
        
        }finally{
        
                try{
                
                        if(preparedStatement != null) preparedStatement.close();
                } catch (SQLException ex) {
                
                        ex.printStackTrace();
                }
        
        }
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgMed().setVisible(true);
            }
        });*/
        
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
        
                public void run (){
                
                        login fenetreLogin = new login();
                        fenetreLogin.setVisible(true);
                
                }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualiserRdv;
    private javax.swing.JButton AjouterRdv;
    private javax.swing.JButton AnnulerRdv;
    private javax.swing.JButton ModifierRdv;
    private javax.swing.JButton VoirListRdv;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField age;
    private com.toedter.calendar.JDateChooser date_rdv;
    private javax.swing.JTextField heure_rdv;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> medecin;
    private javax.swing.JTextField motif;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox<String> specialite;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
